config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'api' do
    resources :accounts
    resources :mutations
    resources :debits
    resources :credits
  end

  root 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :mutations
  has_many :credits
  has_many :debits

  validates_presence_of :name, :currency
end

app/models/credit.rb
class Credit < Mutation

  def amount
    abs_amount
  end
end

app/models/debit.rb
class Debit < Mutation

  def amount
    abs_amount * -1.0
  end
end

app/models/mutation.rb
class Mutation < ActiveRecord::Base
  belongs_to :account
  # belongs_to :user # FIXME create user model

  validates_presence_of :type, :abs_amount, :account_id, :datetime
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :currency)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/mutations_controller.rb
class MutationsController < ApplicationController
  before_action :set_mutation, only: [:show, :edit, :update, :destroy]

  # GET /mutations
  # GET /mutations.json
  def index
    @mutations = Mutation.all
  end

  # GET /mutations/1
  # GET /mutations/1.json
  def show
  end

  # GET /mutations/new
  def new
    @mutation = Mutation.new
  end

  # GET /mutations/1/edit
  def edit
  end

  # POST /mutations
  # POST /mutations.json
  def create
    @mutation = Mutation.new(mutation_params)

    respond_to do |format|
      if @mutation.save
        format.html { redirect_to @mutation, notice: 'Mutation was successfully created.' }
        format.json { render :show, status: :created, location: @mutation }
      else
        format.html { render :new }
        format.json { render json: @mutation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutations/1
  # PATCH/PUT /mutations/1.json
  def update
    respond_to do |format|
      if @mutation.update(mutation_params)
        format.html { redirect_to @mutation, notice: 'Mutation was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutation }
      else
        format.html { render :edit }
        format.json { render json: @mutation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutations/1
  # DELETE /mutations/1.json
  def destroy
    @mutation.destroy
    respond_to do |format|
      format.html { redirect_to mutations_url, notice: 'Mutation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutation
      @mutation = Mutation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutation_params
      params.require(:mutation).permit(:type, :abs_amount, :account_id, :datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpenseManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mutations/_form.html.erb
<%= form_for(@mutation) do |f| %>
  <% if @mutation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mutation.errors.count, "error") %> prohibited this mutation from being saved:</h2>

      <ul>
      <% @mutation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mutations/edit.html.erb
<h1>Editing Mutation</h1>

<%= render 'form' %>

<%= link_to 'Show', @mutation %> |
<%= link_to 'Back', mutations_path %>

app/views/mutations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mutations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mutations.each do |mutation| %>
      <tr>
        <td><%= link_to 'Show', mutation %></td>
        <td><%= link_to 'Edit', edit_mutation_path(mutation) %></td>
        <td><%= link_to 'Destroy', mutation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mutation', new_mutation_path %>

app/views/mutations/new.html.erb
<h1>New Mutation</h1>

<%= render 'form' %>

<%= link_to 'Back', mutations_path %>

app/views/mutations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mutation_path(@mutation) %> |
<%= link_to 'Back', mutations_path %>